### ISSUE TITLE
Add a NodeJS backend

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/startup-incubator#13]
Add NodeJS backend to the website. Initially, it should send a "Hello World" to the homepage as a response.

**Comment by CTZxVULKAN** [comment]
Seems pretty good let me take this one up.

**Comment by Amadabh** [comment]
I am interested in doing this issue.

**Comment by adityabisoi** [comment]
@Adi7171 Sure, please go ahead :) Feel free to reach out to me in case of any questions.
