### ISSUE TITLE
Implement login/signup in the project

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/startup-incubator#14]
Implement a login/signup feature to the project, using NodeJS. This should include adding MongoDB as the database, to authenticate the users. 

Please communicate with the mentors to get [MongoDB Atlas](https://www.mongodb.com/cloud/atlas) credentials.

**Comment by rajdama** [comment]
I can do it.

**Comment by rajdama** [comment]
@adityabisoi Please provide atlas creds.

**Comment by adityabisoi** [comment]
Sent in communication channel

**Comment by subhangi2731** [comment]
@rajdama can you please give the status of this issue?

**Comment by thakan25** [comment]
Hey @adityabisoi @subhangi2731 can I proceed with this issue?

**Comment by RujwiDeshmukh** [comment]
@adityabisoi can I work on this issue?

**Comment by adityabisoi** [comment]
@rajdama Please create a PR by tonight, or I'll have to assign it to someone else.

**Comment by thakan25** [comment]
@adityabisoi can you provide me credentials for MongoDB Atlas?

**Comment by adityabisoi** [comment]
Sure, ping me on gitter

**Comment by Shlok1999** [comment]
Please assign me if this issue is still available

**Comment by adityabisoi** [comment]
@thakan25 It's more than 7 days, are you still working on this?

**Comment by thakan25** [comment]
Yes @adityabisoi I will try to complete it by tomorrow eod.

**Comment by manav-06** [comment]
@adityabisoi if it is not yet done, I'd like to work on this issue.

**Comment by adityabisoi** [comment]
Unassigning @thakan25 due to inactivity, @manav-06 You can start working on this asap.

**Comment by manav-06** [comment]
@adityabisoi Can you provide MongoDB atlas creds?

**Comment by adityabisoi** [comment]
@manav-06 Can you ping me on Gitter

**Comment by Gurdeep475** [comment]
I would like to work on this issue under GSSOC`22. Please assign it to me.

**Comment by SiddhantPawar03** [comment]
@adityabisoi  I'm GSSOC'22 Contributor and would like to work on same issue. Would be glad if you assign me this task.

**Comment by Tejas-117** [comment]
@adityabisoi Hey, I am interested to work on this project too!!

**Comment by adityabisoi** [comment]
This issue has already been assigned. @Gurdeep475 How do you plan to approach this issue?

**Comment by Tejas-117** [comment]
@adityabisoi  We can divide the feature, like I can make frontend or backend and the other can be tackled by @Gurdeep475 ??

**Comment by adityabisoi** [comment]
@Gurdeep475 Your comments?

**Comment by Gurdeep475** [comment]
@adityabisoi but PR can only be made by 1 contributor. one suggestion is to, make a separate issue for frontend implementation of login and signup and this would be for the backend only. I would like to work on the backend part.

**Comment by Gurdeep475** [comment]
> How do you plan to approach this issue?

- I would assume getting username and password from the signup API endpoint, will save them to MongoDB.
- for login, after successful authentication, API will send back JWT to the front-end, will be referred for every later API request that require the user to be authenticated.

**Comment by Tejas-117** [comment]
That's alright for me. 
@adityabisoi I have created a issue can you assign it to me??

**Comment by adityabisoi** [comment]
@Gurdeep475 @Tejas-117 You both can do this together.

**Comment by Gurdeep475** [comment]
Backend work is done, I will make PR Tommarrow.

**Comment by adityabisoi** [comment]
@Gurdeep475 Updates on this issue?

**Comment by ayush25102001** [comment]
> Implement a login/signup feature to the project, using NodeJS. This should include adding MongoDB as the database, to authenticate the users.
> 
> Please communicate with the mentors to get [MongoDB Atlas](https://www.mongodb.com/cloud/atlas) credentials.

Can I work on this @adityabisoi sir

**Comment by ayush25102001** [comment]
> Implement a login/signup feature to the project, using NodeJS. This should include adding MongoDB as the database, to authenticate the users.
> 
> Please communicate with the mentors to get [MongoDB Atlas](https://www.mongodb.com/cloud/atlas) credentials.

Can I work on this @adityabisoi sir

**Comment by ayush25102001** [comment]
@adityabisoi sir for this I will require the userModel so please can u merge that PR or suggest any changes to it.
Also please give the cluster credentials

**Comment by adityabisoi** [comment]
Can you ping me on discord

**Comment by Siddhesh777** [comment]
hey @adityabisoi 
I would like to firebase authentication in this project.
