### ISSUE TITLE
Creating a new Route for user to view his projects

### ISSUE THREAD

**Issue by ayush25102001** [adityabisoi/startup-incubator#140]
Providing user with a button in navbar to view his/her projects, this does not show the projects under the createProject form and the user can freely delete his/her projects as before.

Things will look like this :-

Adding product-1

![Screenshot (171)](https://user-images.githubusercontent.com/78008646/170052785-f357b54d-b6e5-4d2e-8606-80fbfd69ef3f.png)

Adding product-2

![Screenshot (176)](https://user-images.githubusercontent.com/78008646/170052966-8025244d-3089-498e-952e-ba1b911c61a8.png)

Product-3

![Screenshot (172)](https://user-images.githubusercontent.com/78008646/170052716-74e00bf6-3f91-4086-bfe4-f3a931210feb.png)
 
Clicking on My products in Navbar to see his/her products(all projects displayed on different route)

![Screenshot (173)](https://user-images.githubusercontent.com/78008646/170053334-7f6be3d1-0168-4e92-9829-329062d865c8.png)

Deleting project-3

![Screenshot (174)](https://user-images.githubusercontent.com/78008646/170053610-e9a91365-9d88-4765-8f49-4d3c31f92d2b.png)

Project-3 gets deleted properly

![Screenshot (175)](https://user-images.githubusercontent.com/78008646/170053677-b109c713-822a-443a-a8f0-6b05508ef6db.png)

**Comment by adityabisoi** [comment]
Looks good.
