### ISSUE TITLE
Owner details

### ISSUE THREAD

**Issue by ayush25102001** [adityabisoi/startup-incubator#172]
The card does not show any details of its owner on the homepage thus I would provide some details like email and name of the owner of that product

![Screenshot (182)](https://user-images.githubusercontent.com/78008646/170659500-abb85cf3-31c7-420a-a036-d079bedfd734.png)

(No owner details)

**Comment by adityabisoi** [comment]
I suppose the name would be enough. We do not need to show the email of the owner.
