### ISSUE TITLE
store the ids of users in database who have liked the particular comment

### ISSUE THREAD

**Issue by Siddhesh777** [adityabisoi/startup-incubator#199]
IDs of the users who have liked the particular comment should be stored in database.

I am contributor at GSSOC'22.
Please assign this issue to me.

**Comment by adityabisoi** [comment]
I do not think this is necessary. The like count is enough. If you think otherwise, please justify

**Comment by Siddhesh777** [comment]
@adityabisoi 
To implement the issue that user should not like the same comment more than once...it is necessary to store the ids of user who have liked the comment once
