### ISSUE TITLE
Add issue template: feature request 

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/startup-incubator#2]
Add an issue template for requesting new features in the project.

**Comment by swathimannem** [comment]
Hi, can I please work on this issue?

**Comment by adityabisoi** [comment]
@swathimannem Go ahead:)

**Comment by abhishekkumar08** [comment]
Can I work on this this?

**Comment by adityabisoi** [comment]
@abhishekkumar08 This has been assigned already

**Comment by adityabisoi** [comment]
@swathimannem Are you working on this issue?

**Comment by unnikrishnan2002** [comment]
@subhangi2731 @adityabisoi I want to work on this
