### ISSUE TITLE
adding routing and product description page

### ISSUE THREAD

**Issue by thakan25** [adityabisoi/startup-incubator#24]
I would like to implement product details page which will show product details on a separate page as we click a product from homepage

**Comment by adityabisoi** [comment]
@thakan25 Sure, go ahead

**Comment by subhangi2731** [comment]
@thakan25 please give me updates on this issue

**Comment by thakan25** [comment]
@subhangi2731 I implemented the product details page, but was clueless after that since we had no database and we may want to render many things on the product details page like comments, likes, and other details related to that specific product. So I thought furthur enhancement may be possible after database integration.
Please do suggest what else can be added.

**Comment by thakan25** [comment]
My initial work has been merged though. I am currently working on signup/login feature
