### ISSUE TITLE
Add pull request template

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/startup-incubator#3]
Add a pull request template to the project.

**Comment by subhangi2731** [comment]
Hey. Can you please assign this issue to me? @adityabisoi

**Comment by adityabisoi** [comment]
@subhangi2731 Go ahead

**Comment by unnikrishnan2002** [comment]
Hey @adityabisoi  I want to work on this issue

**Comment by subhangi2731** [comment]
@unnikrishnan2002 sure go ahead. Also do tag me too in the further issues you create as I will be assigning them

**Comment by unnikrishnan2002** [comment]
Yeah sure @subhangi2731  . Can I work on this tommorow as the coding period starts from tommorow for KWoC?
