### ISSUE TITLE
Make an movable column for showcasing ads 

### ISSUE THREAD

**Issue by pari-hash** [adityabisoi/startup-incubator#34]
I am a contributor at GSSoC 22 and i would want to create a movable window below the nav bar and above the main content so that the ads or even some basic info can be updated there, it would have a minimum of 3 windows.

**Comment by pari-hash** [comment]
Please assign this to me.

**Comment by adityabisoi** [comment]
@pari-hash Can you give me a demo of what you are trying to achieve?
