### ISSUE TITLE
Product and reviews model (database).

### ISSUE THREAD

**Issue by Tejas-117** [adityabisoi/startup-incubator#39]
- Add products model and reviews model using Mongodb (mongoose) in the backend.
- Products model will consist of id (default), heading, description, image_url, and reviews (array). 
- Reviews model will consist of id (default), user (ref), review_body, and created_at (timestamp).

I would like to work on this under GSSOC 2022.

**Comment by Anirudh4656** [comment]
I have already implemented all the features.

**Comment by Tejas-117** [comment]
@Anirudh4656 The issue assigned to you was different right??

**Comment by Anirudh4656** [comment]
I have to add like and comment feature with beckend and frontend. So for beckend functionality i have to set up models, router. To write comment in specific product, I have to dynamically render I'd. Of specific product. So as things required I implemented all the features.

**Comment by Tejas-117** [comment]
@Anirudh4656  update the description of your issue, so that no one would open same issue again.
