### ISSUE TITLE
Add a homepage for listing products

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/startup-incubator#4]
Add a homepage to the project for listing the products, following the wireframe in the documentation: https://bit.ly/2J5XSHm

**Comment by sreechand2002** [comment]
i want to work on this, please assign it to me

**Comment by adityabisoi** [comment]
@sreechand2002 Sure

**Comment by sreechand2002** [comment]
what about the logo and the required images , should i put one of my choice and will that be provided

**Comment by adityabisoi** [comment]
Add the Logo as in README. Placeholder images must be used in place of company logo.
