### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Siddhesh777** [adityabisoi/startup-incubator#41]
**Describe the bug**
The Like button is not working 

**To Reproduce**
- Steps to reproduce the behavior:
1. We can use react hook useState to increment likes (even for the dislike) 

**Expected behavior**
- It will display total no of likes for each product

**Screenshots**
![issue2](https://user-images.githubusercontent.com/77476772/156888205-be0746b2-f7e8-4a0d-a36c-ae6ef8986317.png)

**Additional details**
I am contributor at gssoc'22
Please assign this task to me.

**Comment by adityabisoi** [comment]
@Siddhesh777 Updates on this issue?

**Comment by Siddhesh777** [comment]
hello @adityabisoi 
I am getting some problem while opening this repo locally
Can you help me with this?
I am getting this error 👇🏻
![1](https://user-images.githubusercontent.com/77476772/160273739-0a0badc2-7486-4552-8ffe-64904d219b4f.png)

**Comment by adityabisoi** [comment]
Did the site run successfully?

**Comment by Siddhesh777** [comment]
@adityabisoi 
No,It didn't.

**Comment by adityabisoi** [comment]
@Siddhesh777 What's the exact error on your terminal?

**Comment by Siddhesh777** [comment]
hey @adityabisoi I am getting the following error
![Screenshot 2022-03-28 at 1 25 27 PM](https://user-images.githubusercontent.com/77476772/160352438-0fb89ad2-8cf0-42eb-ba80-93fc9b2d863a.png)

**Comment by adityabisoi** [comment]
These appear to be warnings, not errors. Have you installed all the required packages and ran the commands correctly? Do you see any error poping up?

**Comment by Siddhesh777** [comment]
yes @adityabisoi 
I have installed all the packages.
The same thing is happening with one of my friend too.

**Comment by adityabisoi** [comment]
@Siddhesh777 Can you ping me on discord

**Comment by Siddhesh777** [comment]
@adityabisoi 
There was some system problem..
I corrected it.
It's working now.
I will PR it asap
