### ISSUE TITLE
Confirm Passoword field.

### ISSUE THREAD

**Issue by ayush25102001** [adityabisoi/startup-incubator#52]
Can I add a confirm password field to the signUp form such that when the user signs up to the appilication we reconfirm the password he sets.
Participant under Gssoc'22.

**Comment by adityabisoi** [comment]
@ayush25102001 Updates on this issue?

**Comment by ayush25102001** [comment]
> @ayush25102001 Updates on this issue?

Sir I will make a PR till tomorrow evening.
