### ISSUE TITLE
Adding Firebase authentication in the project.

### ISSUE THREAD

**Issue by Siddhesh777** [adityabisoi/startup-incubator#60]
**Describe the bug**
Currently the project is not validating the details while loggin in.
I would like to add firebase authentication in our project which will authenticate the user.

**Additional details**
I am contributor at GSSOC'22.
Please assign this issue to me.

**Comment by adityabisoi** [comment]
Login/Signup in covered in #14 , you can comment there if you want to work on that. Please close this one.
