### ISSUE TITLE
Bug report:Product should be added only after loggin in

### ISSUE THREAD

**Issue by Siddhesh777** [adityabisoi/startup-incubator#61]
**Describe the bug**
I think the user should be able to add new product only if he/she is logged in .

**To Reproduce**
- Steps to reproduce the behavior:
1. I will first authenticate the user.
2. If user is logged in then only he should be able to add a new product.

**Screenshots**
![1](https://user-images.githubusercontent.com/77476772/161371489-2bb0fcea-9fce-43c3-b535-01df66b04767.png)

**Additional details**
I am contributor at GSSOC'22.
Please assign this issue to me.

**Comment by adityabisoi** [comment]
Authentication issue already taken
