### ISSUE TITLE
Login/SignUp endpoints and Authentication

### ISSUE THREAD

**Issue by ayush25102001** [adityabisoi/startup-incubator#64]
Can I create the login and signUp API endpoints at the backend through which the user info gets stored inside the database on signUp, while on login the credentials are compared with the credentials set during login and messages are given accordingly.
Also I will make use of JWT token for authentication purpose where the user would be able to access the protected routes of the application only on authentication.
I wish to work on the backend part of the issue.

Participant under Gssoc'22.

**Comment by adityabisoi** [comment]
Related issue already created https://github.com/adityabisoi/startup-incubator/issues/14

You can comment there if you want
