### ISSUE TITLE
Secure and full blown authentication using JWT and configuring a MongoDB database for data storage.

### ISSUE THREAD

**Issue by dasgupta002** [adityabisoi/startup-incubator#68]
Being a backend developer I want to add a full auth flow using JWT's as it is quite secure as well a standard for auth. The PR's and issues raised here relating to auth are not up to the mark and no work hands down has been done till date constructively. I want to resolve the matter at one shot.
Firebase auth to me is worthless here as it could bring loads of headbutt and lead to becoming a barrier for future backend add-on's.
MongoDB must be configured properly to store all product data as well as a storage tier for any feature improvement's in future.
As a contributor in GSSOC '22, please assign me this issue as I am keen on working on this segment.

**Comment by adityabisoi** [comment]
@dasgupta002 All other dependencies have been cleared, you can work on this if you want now.
