### ISSUE TITLE
Auhentication(Backend)

### ISSUE THREAD

**Issue by ayush25102001** [adityabisoi/startup-incubator#79]
Can I set up authentication using JsonWebTokens(JWT) at the backend here when the logsIn or SignsUp to our application we provide the user with a token which is then verified before the user is allowed to access the protected routes of our application.
Participant under Gssoc'22

**Comment by ayush25102001** [comment]
I will also handle the frontend part of this where I will store the token in the local storage which will be an indication whether the user is verified and if not instead of showing the homepage I will direct him to the login route.
Can I work on this @adityabisoi

**Comment by adityabisoi** [comment]
Related issue already created. Look out for updates on authentication, I shall open a new issue if needed

**Comment by ayush25102001** [comment]
@adityabisoi can u assign me this
