### ISSUE TITLE
Welcome email

### ISSUE THREAD

**Issue by ayush25102001** [adityabisoi/startup-incubator#98]
Can I add a the functionality where on successfull signUp the user would receive an email.
Though this will be in the spam section.
Can I work on this as participant of gssoc’22

**Comment by adityabisoi** [comment]
Nice idea, but we need authentication implemented first.

**Comment by adityabisoi** [comment]
@ayush25102001 You can create an issue for authentication if you want, as I see no one else is working on it currently.

**Comment by navyasharma0203** [comment]
Can I work on this??

**Comment by adityabisoi** [comment]
@ayush25102001 Most of the email senders, unless paid, send emails that end up in spam. So,  I don't think this feature would create much of a difference. Let's abandon this issue.

**Comment by ayush25102001** [comment]
> @ayush25102001 Most of the email senders, unless paid, send emails that end up in spam. So, I don't think this feature would create much of a difference. Let's abandon this issue.

Ok., let’s leave it

**Comment by Siddhesh777** [comment]
hello @adityabisoi 
If we send emails using nodemailer then they are present in our normal inbox and not spam folder.
If you wish I would like to work on this issue.
